version: 0.2

phases:
  install:
    commands:
      - # Add your installation commands here

  pre_build:
    commands:
      - # Add any pre-build commands here

  build:
    commands:
      - |
        # Check for changes in First
        if git diff --quiet HEAD^ HEAD -- First; then
          echo "No changes detected in First"
        else
          echo "Changes detected in First"
          cd $CODEBUILD_SRC_DIR
          zip -j hello-python.zip First/*
          aws s3 cp hello-python.zip s3://npj-terraform-state/
        fi

        # Check for changes in Second
        if git diff --quiet HEAD^ HEAD -- Second; then
          echo "No changes detected in Second"
        else
          echo "Changes detected in Second"
          cd $CODEBUILD_SRC_DIR
          zip -j hi-python.zip Second/*
          aws s3 cp hi-python.zip s3://npj-terraform-state/
        fi
        
  post_build:
    commands:
      - # Add any post-build commands here
